--
-- PostgreSQL database dump
--

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-09-24 13:00:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 22211)
-- Name: cash_registers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cash_registers (
    id bigint NOT NULL,
    active boolean,
    cash_sales numeric(38,2),
    closed_at timestamp(6) without time zone,
    counted_amount numeric(38,2),
    credit_sales numeric(38,2),
    debit_sales numeric(38,2),
    difference numeric(38,2),
    expected_amount numeric(38,2),
    opened_at timestamp(6) without time zone,
    opening_amount numeric(38,2),
    total_sales numeric(38,2),
    total_tickets integer NOT NULL
);


ALTER TABLE public.cash_registers OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 22210)
-- Name: cash_registers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cash_registers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_registers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 22219)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 22218)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 22227)
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount numeric(38,2),
    attempt_count integer,
    authorization_code character varying(255),
    card_brand character varying(255),
    card_type character varying(255),
    create_at timestamp(6) without time zone,
    error_message character varying(255),
    last_four_digits character varying(255),
    last_status_query timestamp(6) without time zone,
    payment_date timestamp(6) without time zone,
    payment_method character varying(255),
    response_code character varying(255),
    response_message character varying(255),
    reversal_attemp_count integer,
    reversal_date timestamp(6) without time zone,
    reversal_error_message character varying(255),
    reversal_reason character varying(255),
    reversal_transaction_id character varying(255),
    status character varying(255),
    status_queried boolean NOT NULL,
    transaction_id character varying(255) NOT NULL,
    update_at timestamp(6) without time zone,
    sale_id bigint,
    CONSTRAINT payments_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'DEBIT'::character varying, 'CREDIT'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'REVERSED'::character varying, 'REVERSAL_PENDING'::character varying, 'REVERSAL_FAILED'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 22226)
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 22240)
-- Name: permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissions (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT permissions_name_check CHECK (((name)::text = ANY ((ARRAY['VER_COMPRAS'::character varying, 'CREAR_COMPRAS'::character varying, 'CANCELAR_COMPRAS'::character varying, 'VER_PROVEEDORES'::character varying, 'CREAR_PROVEEDORES'::character varying, 'EDITAR_PROVEEDORES'::character varying, 'ELIMINAR_PROVEEDORES'::character varying, 'VER_PRODUCTOS'::character varying, 'CREAR_PRODUCTOS'::character varying, 'EDITAR_PRODUCTOS'::character varying, 'ELIMINAR_PRODUCTOS'::character varying, 'DESACTIVAR_PRODUCTOS'::character varying, 'ACTIVAR_PRODUCTOS'::character varying, 'VER_USUARIOS'::character varying, 'CREAR_USUARIOS'::character varying, 'EDITAR_USUARIOS'::character varying, 'ACTIVAR_USUARIOS'::character varying, 'DESACTIVAR_USUARIOS'::character varying, 'VER_CATEGORIAS'::character varying, 'CREAR_CATEGORIAS'::character varying, 'EDITAR_CATEGORIAS'::character varying, 'ELIMINAR_CATEGORIAS'::character varying, 'VER_VENTAS'::character varying, 'CREAR_VENTAS'::character varying, 'VER_CAJA'::character varying, 'ABRIR_CAJA'::character varying, 'CERRAR_CAJA'::character varying, 'CORTE_CAJA'::character varying, 'VER_ROLES'::character varying, 'CREAR_ROLES'::character varying, 'ELIMINAR_ROLES'::character varying, 'EDITAR_ROLES'::character varying, 'VER_REPORTES'::character varying, 'PROCESAR_PAGOS'::character varying])::text[])))
);


ALTER TABLE public.permissions OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 22239)
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 22249)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    active boolean DEFAULT true NOT NULL,
    barcode character varying(255),
    cost numeric(10,2),
    img character varying(255),
    name character varying(255) NOT NULL,
    price numeric(38,2) NOT NULL,
    sku character varying(255),
    stock integer NOT NULL,
    category_id bigint
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 22248)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 22263)
-- Name: providers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.providers (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255),
    rfc character varying(255) NOT NULL
);


ALTER TABLE public.providers OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 22262)
-- Name: providers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 22274)
-- Name: purchase_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchase_details (
    id bigint NOT NULL,
    quantity integer,
    subtotal numeric(38,2),
    unit_cost numeric(38,2),
    product_id bigint,
    purchase_id bigint
);


ALTER TABLE public.purchase_details OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 22273)
-- Name: purchase_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchase_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 22281)
-- Name: purchases; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchases (
    id bigint NOT NULL,
    purchase_date timestamp(6) without time zone,
    total numeric(38,2),
    provider_id bigint NOT NULL
);


ALTER TABLE public.purchases OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 22280)
-- Name: purchases_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 22288)
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 22296)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 22295)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 22304)
-- Name: sale_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sale_details (
    id bigint NOT NULL,
    quantity integer,
    subtotal numeric(38,2),
    unit_price numeric(38,2),
    product_id bigint,
    sale_id bigint
);


ALTER TABLE public.sale_details OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 22303)
-- Name: sale_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sale_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 22311)
-- Name: sales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sales (
    id bigint NOT NULL,
    cash_received numeric(38,2),
    change_amount numeric(38,2),
    payment_method character varying(255),
    payment_status character varying(255),
    sale_date timestamp(6) without time zone,
    total numeric(38,2),
    cash_register_id bigint,
    CONSTRAINT sales_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'DEBIT'::character varying, 'CREDIT'::character varying])::text[]))),
    CONSTRAINT sales_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'REVERSED'::character varying, 'REVERSAL_PENDING'::character varying, 'REVERSAL_FAILED'::character varying])::text[])))
);


ALTER TABLE public.sales OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 22310)
-- Name: sales_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 22322)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    reset_token character varying(255),
    reset_token_expiration timestamp(6) without time zone,
    role_id bigint
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 22321)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4883 (class 2606 OID 22217)
-- Name: cash_registers cash_registers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cash_registers
    ADD CONSTRAINT cash_registers_pkey PRIMARY KEY (id);


--
-- TOC entry 4885 (class 2606 OID 22225)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

--
-- TOC entry 4889 (class 2606 OID 22238)
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- TOC entry 4895 (class 2606 OID 22247)
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4899 (class 2606 OID 22261)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 4905 (class 2606 OID 22272)
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
-- TOC entry 4909 (class 2606 OID 22279)
-- Name: purchase_details purchase_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_details
    ADD CONSTRAINT purchase_details_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 22287)
-- Name: purchases purchases_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_pkey PRIMARY KEY (id);


--
-- TOC entry 4915 (class 2606 OID 22302)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 4919 (class 2606 OID 22309)
-- Name: sale_details sale_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sale_details
    ADD CONSTRAINT sale_details_pkey PRIMARY KEY (id);


--
-- TOC entry 4921 (class 2606 OID 22320)
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (id);


--
-- TOC entry 4923 (class 2606 OID 22351)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4913 (class 2606 OID 22294)
-- Name: role_permissions uk_role_permission; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT uk_role_permission PRIMARY KEY (role_id, permission_id);


--
-- TOC entry 4901 (class 2606 OID 22345)
-- Name: products ukfhmd06dsmj6k0n90swsh8ie9g; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT ukfhmd06dsmj6k0n90swsh8ie9g UNIQUE (sku);


--
-- TOC entry 4907 (class 2606 OID 22347)
-- Name: providers ukgwx98vot96l5p58m27wnmhpp8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT ukgwx98vot96l5p58m27wnmhpp8 UNIQUE (rfc);


--
-- TOC entry 4891 (class 2606 OID 22337)
-- Name: payments uklryndveuwa4k5qthti0pkmtlx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uklryndveuwa4k5qthti0pkmtlx UNIQUE (transaction_id);


--
-- TOC entry 4917 (class 2606 OID 22349)
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- TOC entry 4897 (class 2606 OID 22341)
-- Name: permissions ukpnvtwliis6p05pn6i3ndjrqt2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT ukpnvtwliis6p05pn6i3ndjrqt2 UNIQUE (name);


--
-- TOC entry 4903 (class 2606 OID 22343)
-- Name: products ukqfr8vf85k3q1xinifvsl1eynf; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT ukqfr8vf85k3q1xinifvsl1eynf UNIQUE (barcode);


--
-- TOC entry 4887 (class 2606 OID 22335)
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- TOC entry 4893 (class 2606 OID 22339)
-- Name: payments uktjbeijg3xs602k6b8v42dppt4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uktjbeijg3xs602k6b8v42dppt4 UNIQUE (sale_id);


--
-- TOC entry 4925 (class 2606 OID 22333)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4933 (class 2606 OID 22392)
-- Name: sale_details fk6nruj5m7ntwhc29etigqnlk0m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sale_details
    ADD CONSTRAINT fk6nruj5m7ntwhc29etigqnlk0m FOREIGN KEY (sale_id) REFERENCES public.sales(id);


--
-- TOC entry 4928 (class 2606 OID 22367)
-- Name: purchase_details fk8nalokyn4ap9ebeo5hjjximls; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_details
    ADD CONSTRAINT fk8nalokyn4ap9ebeo5hjjximls FOREIGN KEY (purchase_id) REFERENCES public.purchases(id);


--
-- TOC entry 4930 (class 2606 OID 22372)
-- Name: purchases fkbn2k5burari3lcgietiifq9ho; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT fkbn2k5burari3lcgietiifq9ho FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- TOC entry 4935 (class 2606 OID 22397)
-- Name: sales fkcommwxg2dcbxmlw3y6vx9uwwg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fkcommwxg2dcbxmlw3y6vx9uwwg FOREIGN KEY (cash_register_id) REFERENCES public.cash_registers(id);


--
-- TOC entry 4929 (class 2606 OID 22362)
-- Name: purchase_details fkcxl0u6f0whli7bhn1q8ja0ba3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_details
    ADD CONSTRAINT fkcxl0u6f0whli7bhn1q8ja0ba3 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 4931 (class 2606 OID 22377)
-- Name: role_permissions fkegdk29eiy7mdtefy5c7eirr6e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkegdk29eiy7mdtefy5c7eirr6e FOREIGN KEY (permission_id) REFERENCES public.permissions(id);


--
-- TOC entry 4926 (class 2606 OID 22352)
-- Name: payments fkl5ax948m03dbdcy3i0aql4jil; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkl5ax948m03dbdcy3i0aql4jil FOREIGN KEY (sale_id) REFERENCES public.sales(id);


--
-- TOC entry 4932 (class 2606 OID 22382)
-- Name: role_permissions fkn5fotdgk8d1xvo8nav9uv3muc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkn5fotdgk8d1xvo8nav9uv3muc FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 4927 (class 2606 OID 22357)
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- TOC entry 4936 (class 2606 OID 22402)
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 4934 (class 2606 OID 22387)
-- Name: sale_details fkqvh82ispfukxa2yssnok0m12o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sale_details
    ADD CONSTRAINT fkqvh82ispfukxa2yssnok0m12o FOREIGN KEY (product_id) REFERENCES public.products(id);


-- Completed on 2026-09-24 13:00:06

--
-- PostgreSQL database dump complete
--


