--Un negocio tiene pocas cajas físicas y muchos turnos

-- 1. cash_boxes: el registro de cajas físicas del local

CREATE TABLE IF NOT EXISTS public.cash_boxes(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    number varchar(30) NOT NULL,
    descripcion varchar(100),
    active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone,
    CONSTRAINT cash_boxes_pkey PRIMARY KEY(id),
    CONSTRAINT cash_boxes_number_key UNIQUE(number)
);

COMMENT ON TABLE public.cash_boxes IS 
    'Registro de las cajas fisicas del local (CAJA 1, CAJA 2, ...)'
    'Una caja se puede abrir y cerrar muchas veces: cada apertura crea una fila en cash_registers';

COMMENT ON TABLE public.cash_boxes.number IS
    'Numero de la caja fisica. UNIQUE: es lo que el cajero reconoce y elige al abrir';

COMMENT ON TABLE public.cash_boxes.descripcion IS
    'Descripcion libre';

COMMENT ON TABLE public.cash_boxes.active IS
    'false = caja dada de baja, ya no se ofrece para abir, pero no se porque sus cortes existen.';

CREATE INDEX IF NOT EXISTS idx_cash_boxes_active ON public.cash_boxes (active);

--2. Backfill: cada caja que ya exista en cash_registers se vuelve una caja

INSERT INTO public.cash_boxes (number, descripcion, active, created_at)
SELECT DISTINCT c.number, 
                'Caja migrada de los cortes existentes',
                true,
                CURRENT_TIMESTAMP
    FROM public.cash_registers c 
        WHERE c.number IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.cash_boxes b WHERE b.number = c.number);


--3. cash_registers apunta a su caja
ALTER TABLE public.cash_registers ADD COLUMUN IF NOT EXISTS cash_box_id bigint;

--Cada corte se asigna a la caja con el mismo número que tenía
UPDATE public.cash_registers c
SET cash_box_id = b.id
FROM public.cash_boxes b
WHERE b.number = c.number AND c.cash_box_id IS NULL;

--Si algún corte quedó sin caja, se crea una para que ninguno quede huérfano
--Un corte sin caja no se podría mostrar en ningún reporte
INSERT INTO public.cash_boxes (number, descripcion, active, created_at)
SELECT 'CAJA SIN ASIGNAR'
    WHERE EXISTS (
        SELECT 1 FROM public.cash_registers WHERE cash_box_id IS NULL) AND NOT EXISTS (
            SELECT 1 FROM public.cash_boxes WHERE number = 'CAJA SIN ASIGNAR'
        );

UPDATE public.cash_registers c
    SET cash_box_id = (SELECT b.id FROM public.cash_boxes b WHERE b.number = 'CAJA SIN ASIGNAR')
        WHERE c.cash_box_id IS NULL;

--4. El número deja de ser UNIQUE: la caja se abre muchas veces
--Sin esto el segundo turno del día con la misma caja caría 409
ALTER TABLE public.cash_registers DROP CONSTRAINT IF EXISTS cash_register_number_key;

CREATE INDEX IF NOT EXISTS idx_cash_registers_box ON public.cash_registers (cash_box_id);

ALTER TABLE public.cash_registers ADD CONSTRAINT fk_cash_registers_box FOREIGN KEY (cash_box_id) REFERENCES public.cash_boxes(id);

--5. Comentarios actualizados
COMMENT ON COLUMN public.cash_registers.cash_box_id IS 
    'Caja fisica que se abrio. Varias sesiones pueden apuntar a la misma caja';

COMMENT ON COLUMN public.cash_registers.number IS
    'Copia historica del numero de ala caja al abrir. Ya no es UNIQUE: una caja se abre muchas veces';

COMMENT ON COLUMN public.cash_registers.opened_at IS
    'Inicio de esta sesion. Una caja con varias sesiones tiene varias filas';