-- ============================================================================
--  V4__cajas_reutilizables.sql
--  2026-10-01 · Un negocio tiene POCAS cajas físicas y MUCHOS turnos.
--
--  El problema que resuelve
--  -----------------------
--  V3 decidió que "una caja se abre UNA sola vez", porque cash_registers.number
--  era UNIQUE y una fila por caja parecía lo correcto. Pero el dueño aclaró el
--  modelo real: en el local hay DOS cajas (CAJA 1 y CAJA 2) y se abren y
--  cierran VARIAS VECES, en distintos días de la semana.
--
--  Con el UNIQUE, la segunda vez que se abría "CAJA 1" daba 409. Ese día no
--  había forma de volver a abrir la caja que sí existía.
--
--  La solución: separar DOS conceptos que V3 confundía en una sola tabla
--  ---------------------------------------------------------------------
--    cash_boxes     = las CAJAS FÍSICAS del local (2 filas, poco crecen)
--    cash_registers = las SESIONES (una fila por apertura/cierre, crece diario)
--
--  cash_registers sigue siendo la que enlaza con sales.cash_register_id, así
--  que NO hay que tocar SaleEntity ni los reportes de ventas.
--
--  CONSECUENCIA DE DISEÑO: cash_registers.number deja de ser UNIQUE y pasa a ser
--  una COPIA HISTÓRICA del número de la caja al momento de abrir. Se conserva a
--  propósito por dos razones:
--    1. El reporte "filtrar por caja" sigue funcionando sin JOIN.
--    2. Si mañana renombran "CAJA 1" a "CAJA PRINCIPAL", los cortes antiguos deben
--       seguir diciendo "CAJA 1": es la evidencia de cómo se llamaba entonces.
--       Es histórico, y por diseño lo es.
-- ============================================================================

-- ----------------------------------------------------------------------------
--  1) cash_boxes: el registro de cajas físicas del local
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.cash_boxes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    number varchar(50) NOT NULL,
    description varchar(255),
    active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) without time zone,
    CONSTRAINT cash_boxes_pkey PRIMARY KEY (id),
    CONSTRAINT cash_boxes_number_key UNIQUE (number)
);

-- LENGTH: number es varchar(50) y description varchar(255), los MISMOS que
-- declara CashBoxEntity en Java. Si aquí fueran más cortos, Hibernate valida el
-- esquema al arrancar (ddl-auto=validate en producción) y la app no levanta.

COMMENT ON TABLE public.cash_boxes IS
    'Registro de las CAJAS FISICAS del local (CAJA 1, CAJA 2, ...). '
    'Una caja se puede abrir y cerrar muchas veces: cada apertura crea una fila en cash_registers';

-- ESTA ES LA LÍNEA QUE ROMPIÓ EL ARRANQUE (la 20 de la versión anterior).
--
-- Se escribió "COMMENT ON TABLE ... cash_boxes.number", pero eso le dice a
-- PostgreSQL que la tabla se llama "number" DENTRO del esquema "cash_boxes".
-- De ahí el error: cross-database references are not implemented.
--
-- La forma correcta de comentar una COLUMNA es "COMMENT ON COLUMN":
COMMENT ON COLUMN public.cash_boxes.number IS
    'Numero de la caja fisica. UNIQUE: es lo que el cajero reconoce y elige al abrir';

COMMENT ON COLUMN public.cash_boxes.description IS
    'Descripcion libre opcional ("la que esta junto a la puerta")';

COMMENT ON COLUMN public.cash_boxes.active IS
    'false = caja dada de baja: ya no se ofrece para abrir, pero NO se borra porque sus cortes existen';

CREATE INDEX IF NOT EXISTS idx_cash_boxes_active ON public.cash_boxes (active);

-- ----------------------------------------------------------------------------
--  2) Backfill: cada caja que ya exista en cash_registers se vuelve una caja
-- ----------------------------------------------------------------------------
--  Los cortes de V3 tienen un número en cash_registers.number. Cada número
--  distinto se crea como caja, para que al abrir de nuevo "CAJA 1" funcione y
--  el historial quede bajo esa caja.
--
--  NOT EXISTS evita duplicar si la migración se corre dos veces.

INSERT INTO public.cash_boxes (number, description, active, created_at)
SELECT DISTINCT c.number,
       'Caja migrada de los cortes existentes',
       true,
       CURRENT_TIMESTAMP
FROM public.cash_registers c
WHERE c.number IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM public.cash_boxes b WHERE b.number = c.number);

-- ----------------------------------------------------------------------------
--  3) cash_registers apunta a su caja
-- ----------------------------------------------------------------------------

ALTER TABLE public.cash_registers
    ADD COLUMN IF NOT EXISTS cash_box_id bigint;

-- Cada corte se asigna a la caja con el MISMO número que tenía.
UPDATE public.cash_registers c
SET cash_box_id = b.id
FROM public.cash_boxes b
WHERE b.number = c.number
  AND c.cash_box_id IS NULL;

-- Si algún corte quedó sin caja (número raro), se crea una para que ninguno
-- quede huérfano: un corte sin caja no se podría mostrar en ningún reporte.
--
-- "SELECT ... WHERE EXISTS" sin FROM es válido en PostgreSQL: es un SELECT de
-- una sola fila que solo se materializa si la condición se cumple.
INSERT INTO public.cash_boxes (number, description, active, created_at)
SELECT 'CAJA SIN ASIGNAR',
       'Agrupa cortes cuyo numero no coincide con ninguna caja',
       true,
       CURRENT_TIMESTAMP
WHERE EXISTS (
    SELECT 1 FROM public.cash_registers WHERE cash_box_id IS NULL
) AND NOT EXISTS (
    SELECT 1 FROM public.cash_boxes WHERE number = 'CAJA SIN ASIGNAR'
);

UPDATE public.cash_registers c
SET cash_box_id = (SELECT b.id FROM public.cash_boxes b WHERE b.number = 'CAJA SIN ASIGNAR')
WHERE c.cash_box_id IS NULL;

-- ----------------------------------------------------------------------------
--  4) El número deja de ser UNIQUE: la caja se abre muchas veces
-- ----------------------------------------------------------------------------
--  Este es EL cambio de la migración. Sin esto, el segundo turno del día con la
--  misma caja daría 409.
--
-- EL NOMBRE DEL CONSTRAINT: V3 lo creó como "cash_registers_number_key" (con
-- "registers" en plural, que es el nombre de la TABLA). La versión anterior de
-- este archivo.drop "cash_register_number_key" (en singular), que NO existe: el
-- DROP se iba sin hacer nada, el UNIQUE sobrevivía, y el 409 seguiría
-- apareciendo al reabrir una caja. Es el bug más silencioso de esta migración,
-- porque no da ningún error: simplemente no hace nada.
--
--  El IF EXISTS protege solo contra typos, NO contra el nombre equivocado. Por
--  eso el nombre se copió literal de V3 (línea 146) en vez de escribirse de
--  memoria.
ALTER TABLE public.cash_registers
    DROP CONSTRAINT IF EXISTS cash_registers_number_key;

-- Verificación de que el UNIQUE realmente se fue. Si sobrevive, esta línea
-- revienta con un 500 al arrancar y es MUCHO más claro que descubrirlo al
-- reabrir una caja en producción.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = 'cash_registers'
          AND c.contype = 'u'
          AND c.conkey = ARRAY[
              (SELECT attnum FROM pg_attribute
               WHERE attrelid = t.oid AND attname = 'number')
          ]::smallint[]
    ) THEN
        RAISE EXCEPTION
            'V4 fallo: cash_registers.number sigue con UNIQUE. La caja no podra reabrirse.';
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_cash_registers_box ON public.cash_registers (cash_box_id);

ALTER TABLE public.cash_registers
    ADD CONSTRAINT fk_cash_registers_box
    FOREIGN KEY (cash_box_id) REFERENCES public.cash_boxes(id);

-- ----------------------------------------------------------------------------
--  5) Comentarios actualizados
-- ----------------------------------------------------------------------------

COMMENT ON COLUMN public.cash_registers.cash_box_id IS
    'Caja fisica que se abrio. Varias sesiones pueden apuntar a la misma caja';

COMMENT ON COLUMN public.cash_registers.number IS
    'COPIA HISTORICA del numero de la caja al abrir. YA NO es UNIQUE: una caja se abre muchas veces';

COMMENT ON COLUMN public.cash_registers.opened_at IS
    'Inicio de ESTA sesion. Una caja con varias sesiones tiene varias filas aqui';